// This file is auto-generated by @hey-api/openapi-ts

export const Body_images_upload_imageSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_images-upload_image'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChoiceSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        },
        correct: {
            type: 'boolean',
            title: 'Correct',
            default: false
        }
    },
    type: 'object',
    required: ['text'],
    title: 'Choice'
} as const;

export const CourseCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description',
            default: 'No Description Added'
        },
        is_open: {
            type: 'boolean',
            title: 'Is Open',
            default: true
        },
        course_pin: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Course Pin'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CourseCreate'
} as const;

export const CoursePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        creator_id: {
            type: 'string',
            format: 'uuid',
            title: 'Creator Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        course_pin: {
            type: 'string',
            title: 'Course Pin'
        },
        is_open: {
            type: 'boolean',
            title: 'Is Open'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'creator_id', 'title', 'course_pin', 'is_open'],
    title: 'CoursePublic'
} as const;

export const EnrollMetadataSchema = {
    properties: {
        course_title: {
            type: 'string',
            title: 'Course Title'
        },
        course_pin: {
            type: 'string',
            title: 'Course Pin'
        }
    },
    type: 'object',
    required: ['course_title', 'course_pin'],
    title: 'EnrollMetadata'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NoteCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: 'Untitled'
        },
        note_data: {
            items: {
                '$ref': '#/components/schemas/NoteItem'
            },
            type: 'array',
            title: 'Note Data',
            default: []
        }
    },
    type: 'object',
    title: 'NoteCreate'
} as const;

export const NoteItemSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        flag: {
            type: 'integer',
            title: 'Flag'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        }
    },
    type: 'object',
    required: ['title', 'content', 'flag'],
    title: 'NoteItem'
} as const;

export const NotePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        note_data: {
            items: {
                '$ref': '#/components/schemas/NoteItem'
            },
            type: 'array',
            title: 'Note Data'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'note_data', 'user_id'],
    title: 'NotePublic'
} as const;

export const NoteUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: 'Untitled'
        },
        note_data: {
            items: {
                '$ref': '#/components/schemas/NoteItem'
            },
            type: 'array',
            title: 'Note Data',
            default: []
        }
    },
    type: 'object',
    title: 'NoteUpdate'
} as const;

export const QuestionCreateSchema = {
    properties: {
        question_type: {
            '$ref': '#/components/schemas/QuestionType'
        },
        question_data: {
            '$ref': '#/components/schemas/QuestionTeacherData'
        },
        tag: {
            type: 'string',
            title: 'Tag',
            default: 'untagged'
        },
        total_marks: {
            type: 'integer',
            title: 'Total Marks',
            default: 5
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        }
    },
    type: 'object',
    required: ['question_type', 'question_data'],
    title: 'QuestionCreate',
    description: 'Teacher-authored question submitted when adding to a quiz/test.'
} as const;

export const QuestionStudentResponseSchema = {
    properties: {
        question_type: {
            '$ref': '#/components/schemas/QuestionType'
        },
        user_response: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'boolean'
                }
            ],
            title: 'User Response'
        }
    },
    type: 'object',
    required: ['question_type', 'user_response'],
    title: 'QuestionStudentResponse'
} as const;

export const QuestionTeacherDataSchema = {
    properties: {
        question_type: {
            '$ref': '#/components/schemas/QuestionType'
        },
        question_text: {
            type: 'string',
            title: 'Question Text'
        },
        choices: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/Choice'
                    },
                    type: 'array',
                    maxItems: 6,
                    minItems: 4
                },
                {
                    type: 'null'
                }
            ],
            title: 'Choices'
        },
        true_false_answer: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'True False Answer'
        },
        correct_answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Answer'
        }
    },
    type: 'object',
    required: ['question_type', 'question_text'],
    title: 'QuestionTeacherData'
} as const;

export const QuestionTypeSchema = {
    type: 'string',
    enum: ['single_choice', 'multiple_choice', 'user_input', 'true_false'],
    title: 'QuestionType'
} as const;

export const QuizCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: 'New Quiz'
        },
        total_mark: {
            type: 'integer',
            title: 'Total Mark',
            default: 20
        },
        allowed_attempt: {
            type: 'integer',
            title: 'Allowed Attempt',
            default: 1
        },
        is_unlimited_attempt: {
            type: 'boolean',
            title: 'Is Unlimited Attempt',
            default: false
        }
    },
    type: 'object',
    title: 'QuizCreate'
} as const;

export const StudentAnswerSchema = {
    properties: {
        question_type: {
            '$ref': '#/components/schemas/QuestionType'
        },
        user_response: {
            '$ref': '#/components/schemas/QuestionStudentResponse'
        }
    },
    type: 'object',
    required: ['question_type', 'user_response'],
    title: 'StudentAnswer',
    description: 'Payload a student sends to submit an answer.'
} as const;

export const TestCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            default: 'New Test'
        },
        total_mark: {
            type: 'integer',
            title: 'Total Mark',
            default: 20
        },
        duration: {
            type: 'integer',
            title: 'Duration',
            default: 30
        },
        window_start: {
            type: 'string',
            format: 'date-time',
            title: 'Window Start'
        },
        window_end: {
            type: 'string',
            format: 'date-time',
            title: 'Window End'
        }
    },
    type: 'object',
    required: ['window_start', 'window_end'],
    title: 'TestCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'teacher', 'student'],
    title: 'UserRole',
    description: 'Application roles. Admins are also flagged ``is_superuser``.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;