// This file is auto-generated by @hey-api/openapi-ts

/**
 * A single answer inside a batch (submit-all) submission.
 */
export type BatchAnswer = {
    question_id: string;
    question_type: QuestionType;
    user_response: QuestionStudentResponse;
};

/**
 * Payload for submitting a whole quiz or test at once.
 */
export type BatchSubmission = {
    answers?: Array<BatchAnswer>;
};

export type Body_images_upload_image = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Choice = {
    text: string;
    correct?: boolean;
};

export type CourseCreate = {
    title: string;
    description?: string;
    is_open?: boolean;
    course_pin?: (string | null);
};

export type CoursePublic = {
    id: string;
    creator_id: string;
    title: string;
    description?: (string | null);
    course_pin: string;
    is_open: boolean;
    created_at?: (string | null);
};

export type EnrollMetadata = {
    course_title: string;
    course_pin: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteCreate = {
    title?: string;
    note_data?: Array<NoteItem>;
};

export type NoteItem = {
    title: string;
    content: string;
    flag: number;
    image?: (string | null);
};

export type NotePublic = {
    id: string;
    title: string;
    note_data: Array<NoteItem>;
    user_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type NoteUpdate = {
    title?: string;
    note_data?: Array<NoteItem>;
};

/**
 * Teacher-authored question submitted when adding to a quiz/test.
 */
export type QuestionCreate = {
    question_type: QuestionType;
    question_data: QuestionTeacherData;
    tag?: string;
    total_marks?: number;
    image?: (string | null);
};

export type QuestionStudentResponse = {
    question_type: QuestionType;
    user_response: (string | Array<(string)> | boolean);
};

export type QuestionTeacherData = {
    question_type: QuestionType;
    question_text: string;
    choices?: (Array<Choice> | null);
    true_false_answer?: (boolean | null);
    correct_answer?: (string | null);
};

export type QuestionType = 'single_choice' | 'multiple_choice' | 'user_input' | 'true_false';

export type QuizCreate = {
    title?: string;
    total_mark?: number;
    allowed_attempt?: number;
    is_unlimited_attempt?: boolean;
};

/**
 * Payload a student sends to submit an answer.
 */
export type StudentAnswer = {
    question_type: QuestionType;
    user_response: QuestionStudentResponse;
};

export type TestCreate = {
    title?: string;
    total_mark?: number;
    duration?: number;
    window_start: string;
    window_end: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    role?: UserRole;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Application roles. Admins are also flagged ``is_superuser``.
 */
export type UserRole = 'admin' | 'teacher' | 'student';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    role?: (UserRole | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminAddUserData = {
    requestBody: UserCreate;
};

export type AdminAddUserResponse = (UserPublic);

export type AdminDeleteUnusedImagesResponse = (Message);

export type ImagesUploadImageData = {
    formData: Body_images_upload_image;
};

export type ImagesUploadImageResponse = ({
    [key: string]: (string);
});

export type ImagesShowImageData = {
    filename: string;
};

export type ImagesShowImageResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type StudentGetEnrolledCoursesResponse = (Array<CoursePublic>);

export type StudentEnrollCourseData = {
    requestBody: EnrollMetadata;
};

export type StudentEnrollCourseResponse = (unknown);

export type StudentGetQuizzesAndTestsData = {
    courseTitle: string;
};

export type StudentGetQuizzesAndTestsResponse = ({
    [key: string]: unknown;
});

export type StudentGetQuizQuestionsData = {
    courseTitle: string;
    quizId: string;
};

export type StudentGetQuizQuestionsResponse = (unknown);

export type StudentStartTestData = {
    courseTitle: string;
    testId: string;
};

export type StudentStartTestResponse = (unknown);

export type StudentGetTestQuestionsData = {
    courseTitle: string;
    testId: string;
};

export type StudentGetTestQuestionsResponse = (unknown);

export type StudentSubmitQuizData = {
    courseTitle: string;
    quizId: string;
    requestBody: BatchSubmission;
};

export type StudentSubmitQuizResponse = (unknown);

export type StudentSubmitTestData = {
    courseTitle: string;
    requestBody: BatchSubmission;
    testId: string;
};

export type StudentSubmitTestResponse = (unknown);

export type StudentSubmitAnswerData = {
    courseTitle: string;
    questionId: string;
    questionSetId: string;
    requestBody: StudentAnswer;
};

export type StudentSubmitAnswerResponse = (unknown);

export type StudentGetNotesResponse = (Array<NotePublic>);

export type StudentCreateNoteData = {
    requestBody: NoteCreate;
};

export type StudentCreateNoteResponse = (NotePublic);

export type StudentGetNoteData = {
    noteId: string;
};

export type StudentGetNoteResponse = (NotePublic);

export type StudentUpdateNoteData = {
    noteId: string;
    requestBody: NoteUpdate;
};

export type StudentUpdateNoteResponse = (NotePublic);

export type StudentDeleteNoteData = {
    noteId: string;
};

export type StudentDeleteNoteResponse = (NotePublic);

export type TeacherGetCoursesResponse = (Array<CoursePublic>);

export type TeacherCreateCourseData = {
    requestBody: CourseCreate;
};

export type TeacherCreateCourseResponse = (CoursePublic);

export type TeacherGetQuizzesAndTestsData = {
    courseTitle: string;
};

export type TeacherGetQuizzesAndTestsResponse = ({
    [key: string]: unknown;
});

export type TeacherGetEnrolledStudentsData = {
    courseTitle: string;
};

export type TeacherGetEnrolledStudentsResponse = (Array<UserPublic>);

export type TeacherCreateQuizData = {
    courseTitle: string;
    requestBody: QuizCreate;
};

export type TeacherCreateQuizResponse = (unknown);

export type TeacherCreateTestData = {
    courseTitle: string;
    requestBody: TestCreate;
};

export type TeacherCreateTestResponse = (unknown);

export type TeacherGetQuestionsInQuizData = {
    courseTitle: string;
    quizId: string;
};

export type TeacherGetQuestionsInQuizResponse = (unknown);

export type TeacherCreateQuestionInQuizData = {
    courseTitle: string;
    quizId: string;
    requestBody: QuestionCreate;
};

export type TeacherCreateQuestionInQuizResponse = (Message);

export type TeacherGetQuestionsInTestData = {
    courseTitle: string;
    testId: string;
};

export type TeacherGetQuestionsInTestResponse = (unknown);

export type TeacherCreateQuestionInTestData = {
    courseTitle: string;
    requestBody: QuestionCreate;
    testId: string;
};

export type TeacherCreateQuestionInTestResponse = (Message);

export type TeacherGetQuizProgressData = {
    courseTitle: string;
    quizId: string;
};

export type TeacherGetQuizProgressResponse = (unknown);

export type TeacherGetTestProgressData = {
    courseTitle: string;
    testId: string;
};

export type TeacherGetTestProgressResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);