/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutProfileImport } from './routes/_layout/profile'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as LayoutteacherHostLiveImport } from './routes/_layout/(teacher)/hostLive'
import { Route as LayoutteacherCoursesImport } from './routes/_layout/(teacher)/courses'
import { Route as LayoutstudentNotesImport } from './routes/_layout/(student)/notes'
import { Route as LayoutstudentJoinLiveImport } from './routes/_layout/(student)/joinLive'
import { Route as LayoutstudentEnrolledCoursesImport } from './routes/_layout/(student)/enrolledCourses'
import { Route as LayoutadminDashboardImport } from './routes/_layout/(admin)/dashboard'
import { Route as LayoutadminAddUserImport } from './routes/_layout/(admin)/addUser'
import { Route as LayoutteacherCoursesIndexImport } from './routes/_layout/(teacher)/courses.index'
import { Route as LayoutstudentEnrolledCourssesIndexImport } from './routes/_layout/(student)/enrolledCoursses.index'
import { Route as LayoutteacherCoursesCourseTltleImport } from './routes/_layout/(teacher)/courses.$courseTltle'
import { Route as LayoutstudentEnrolledCoursesCourseTitleImport } from './routes/_layout/(student)/enrolledCourses.$courseTitle'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileRoute = LayoutProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)

const authSignupRoute = authSignupImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutteacherHostLiveRoute = LayoutteacherHostLiveImport.update({
  id: '/(teacher)/hostLive',
  path: '/hostLive',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutteacherCoursesRoute = LayoutteacherCoursesImport.update({
  id: '/(teacher)/courses',
  path: '/courses',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutstudentNotesRoute = LayoutstudentNotesImport.update({
  id: '/(student)/notes',
  path: '/notes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutstudentJoinLiveRoute = LayoutstudentJoinLiveImport.update({
  id: '/(student)/joinLive',
  path: '/joinLive',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutstudentEnrolledCoursesRoute =
  LayoutstudentEnrolledCoursesImport.update({
    id: '/(student)/enrolledCourses',
    path: '/enrolledCourses',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutadminDashboardRoute = LayoutadminDashboardImport.update({
  id: '/(admin)/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutadminAddUserRoute = LayoutadminAddUserImport.update({
  id: '/(admin)/addUser',
  path: '/addUser',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutteacherCoursesIndexRoute = LayoutteacherCoursesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutteacherCoursesRoute,
} as any)

const LayoutstudentEnrolledCourssesIndexRoute =
  LayoutstudentEnrolledCourssesIndexImport.update({
    id: '/(student)/enrolledCoursses/',
    path: '/enrolledCoursses/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutteacherCoursesCourseTltleRoute =
  LayoutteacherCoursesCourseTltleImport.update({
    id: '/$courseTltle',
    path: '/$courseTltle',
    getParentRoute: () => LayoutteacherCoursesRoute,
  } as any)

const LayoutstudentEnrolledCoursesCourseTitleRoute =
  LayoutstudentEnrolledCoursesCourseTitleImport.update({
    id: '/$courseTitle',
    path: '/$courseTitle',
    getParentRoute: () => LayoutstudentEnrolledCoursesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(admin)/addUser': {
      id: '/_layout/(admin)/addUser'
      path: '/addUser'
      fullPath: '/addUser'
      preLoaderRoute: typeof LayoutadminAddUserImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(admin)/dashboard': {
      id: '/_layout/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutadminDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(student)/enrolledCourses': {
      id: '/_layout/(student)/enrolledCourses'
      path: '/enrolledCourses'
      fullPath: '/enrolledCourses'
      preLoaderRoute: typeof LayoutstudentEnrolledCoursesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(student)/joinLive': {
      id: '/_layout/(student)/joinLive'
      path: '/joinLive'
      fullPath: '/joinLive'
      preLoaderRoute: typeof LayoutstudentJoinLiveImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(student)/notes': {
      id: '/_layout/(student)/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof LayoutstudentNotesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(teacher)/courses': {
      id: '/_layout/(teacher)/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutteacherCoursesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(teacher)/hostLive': {
      id: '/_layout/(teacher)/hostLive'
      path: '/hostLive'
      fullPath: '/hostLive'
      preLoaderRoute: typeof LayoutteacherHostLiveImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(student)/enrolledCourses/$courseTitle': {
      id: '/_layout/(student)/enrolledCourses/$courseTitle'
      path: '/$courseTitle'
      fullPath: '/enrolledCourses/$courseTitle'
      preLoaderRoute: typeof LayoutstudentEnrolledCoursesCourseTitleImport
      parentRoute: typeof LayoutstudentEnrolledCoursesImport
    }
    '/_layout/(teacher)/courses/$courseTltle': {
      id: '/_layout/(teacher)/courses/$courseTltle'
      path: '/$courseTltle'
      fullPath: '/courses/$courseTltle'
      preLoaderRoute: typeof LayoutteacherCoursesCourseTltleImport
      parentRoute: typeof LayoutteacherCoursesImport
    }
    '/_layout/(student)/enrolledCoursses/': {
      id: '/_layout/(student)/enrolledCoursses/'
      path: '/enrolledCoursses'
      fullPath: '/enrolledCoursses'
      preLoaderRoute: typeof LayoutstudentEnrolledCourssesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/(teacher)/courses/': {
      id: '/_layout/(teacher)/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutteacherCoursesIndexImport
      parentRoute: typeof LayoutteacherCoursesImport
    }
  }
}

// Create and export the route tree

interface LayoutstudentEnrolledCoursesRouteChildren {
  LayoutstudentEnrolledCoursesCourseTitleRoute: typeof LayoutstudentEnrolledCoursesCourseTitleRoute
}

const LayoutstudentEnrolledCoursesRouteChildren: LayoutstudentEnrolledCoursesRouteChildren =
  {
    LayoutstudentEnrolledCoursesCourseTitleRoute:
      LayoutstudentEnrolledCoursesCourseTitleRoute,
  }

const LayoutstudentEnrolledCoursesRouteWithChildren =
  LayoutstudentEnrolledCoursesRoute._addFileChildren(
    LayoutstudentEnrolledCoursesRouteChildren,
  )

interface LayoutteacherCoursesRouteChildren {
  LayoutteacherCoursesCourseTltleRoute: typeof LayoutteacherCoursesCourseTltleRoute
  LayoutteacherCoursesIndexRoute: typeof LayoutteacherCoursesIndexRoute
}

const LayoutteacherCoursesRouteChildren: LayoutteacherCoursesRouteChildren = {
  LayoutteacherCoursesCourseTltleRoute: LayoutteacherCoursesCourseTltleRoute,
  LayoutteacherCoursesIndexRoute: LayoutteacherCoursesIndexRoute,
}

const LayoutteacherCoursesRouteWithChildren =
  LayoutteacherCoursesRoute._addFileChildren(LayoutteacherCoursesRouteChildren)

interface LayoutRouteChildren {
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutadminAddUserRoute: typeof LayoutadminAddUserRoute
  LayoutadminDashboardRoute: typeof LayoutadminDashboardRoute
  LayoutstudentEnrolledCoursesRoute: typeof LayoutstudentEnrolledCoursesRouteWithChildren
  LayoutstudentJoinLiveRoute: typeof LayoutstudentJoinLiveRoute
  LayoutstudentNotesRoute: typeof LayoutstudentNotesRoute
  LayoutteacherCoursesRoute: typeof LayoutteacherCoursesRouteWithChildren
  LayoutteacherHostLiveRoute: typeof LayoutteacherHostLiveRoute
  LayoutstudentEnrolledCourssesIndexRoute: typeof LayoutstudentEnrolledCourssesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutadminAddUserRoute: LayoutadminAddUserRoute,
  LayoutadminDashboardRoute: LayoutadminDashboardRoute,
  LayoutstudentEnrolledCoursesRoute:
    LayoutstudentEnrolledCoursesRouteWithChildren,
  LayoutstudentJoinLiveRoute: LayoutstudentJoinLiveRoute,
  LayoutstudentNotesRoute: LayoutstudentNotesRoute,
  LayoutteacherCoursesRoute: LayoutteacherCoursesRouteWithChildren,
  LayoutteacherHostLiveRoute: LayoutteacherHostLiveRoute,
  LayoutstudentEnrolledCourssesIndexRoute:
    LayoutstudentEnrolledCourssesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof LayoutProfileRoute
  '/': typeof LayoutIndexRoute
  '/addUser': typeof LayoutadminAddUserRoute
  '/dashboard': typeof LayoutadminDashboardRoute
  '/enrolledCourses': typeof LayoutstudentEnrolledCoursesRouteWithChildren
  '/joinLive': typeof LayoutstudentJoinLiveRoute
  '/notes': typeof LayoutstudentNotesRoute
  '/courses': typeof LayoutteacherCoursesRouteWithChildren
  '/hostLive': typeof LayoutteacherHostLiveRoute
  '/enrolledCourses/$courseTitle': typeof LayoutstudentEnrolledCoursesCourseTitleRoute
  '/courses/$courseTltle': typeof LayoutteacherCoursesCourseTltleRoute
  '/enrolledCoursses': typeof LayoutstudentEnrolledCourssesIndexRoute
  '/courses/': typeof LayoutteacherCoursesIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof LayoutProfileRoute
  '/': typeof LayoutIndexRoute
  '/addUser': typeof LayoutadminAddUserRoute
  '/dashboard': typeof LayoutadminDashboardRoute
  '/enrolledCourses': typeof LayoutstudentEnrolledCoursesRouteWithChildren
  '/joinLive': typeof LayoutstudentJoinLiveRoute
  '/notes': typeof LayoutstudentNotesRoute
  '/hostLive': typeof LayoutteacherHostLiveRoute
  '/enrolledCourses/$courseTitle': typeof LayoutstudentEnrolledCoursesCourseTitleRoute
  '/courses/$courseTltle': typeof LayoutteacherCoursesCourseTltleRoute
  '/enrolledCoursses': typeof LayoutstudentEnrolledCourssesIndexRoute
  '/courses': typeof LayoutteacherCoursesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/(admin)/addUser': typeof LayoutadminAddUserRoute
  '/_layout/(admin)/dashboard': typeof LayoutadminDashboardRoute
  '/_layout/(student)/enrolledCourses': typeof LayoutstudentEnrolledCoursesRouteWithChildren
  '/_layout/(student)/joinLive': typeof LayoutstudentJoinLiveRoute
  '/_layout/(student)/notes': typeof LayoutstudentNotesRoute
  '/_layout/(teacher)/courses': typeof LayoutteacherCoursesRouteWithChildren
  '/_layout/(teacher)/hostLive': typeof LayoutteacherHostLiveRoute
  '/_layout/(student)/enrolledCourses/$courseTitle': typeof LayoutstudentEnrolledCoursesCourseTitleRoute
  '/_layout/(teacher)/courses/$courseTltle': typeof LayoutteacherCoursesCourseTltleRoute
  '/_layout/(student)/enrolledCoursses/': typeof LayoutstudentEnrolledCourssesIndexRoute
  '/_layout/(teacher)/courses/': typeof LayoutteacherCoursesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/login'
    | '/signup'
    | '/profile'
    | '/'
    | '/addUser'
    | '/dashboard'
    | '/enrolledCourses'
    | '/joinLive'
    | '/notes'
    | '/courses'
    | '/hostLive'
    | '/enrolledCourses/$courseTitle'
    | '/courses/$courseTltle'
    | '/enrolledCoursses'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/signup'
    | '/profile'
    | '/'
    | '/addUser'
    | '/dashboard'
    | '/enrolledCourses'
    | '/joinLive'
    | '/notes'
    | '/hostLive'
    | '/enrolledCourses/$courseTitle'
    | '/courses/$courseTltle'
    | '/enrolledCoursses'
    | '/courses'
  id:
    | '__root__'
    | '/_layout'
    | '/about'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_layout/profile'
    | '/_layout/'
    | '/_layout/(admin)/addUser'
    | '/_layout/(admin)/dashboard'
    | '/_layout/(student)/enrolledCourses'
    | '/_layout/(student)/joinLive'
    | '/_layout/(student)/notes'
    | '/_layout/(teacher)/courses'
    | '/_layout/(teacher)/hostLive'
    | '/_layout/(student)/enrolledCourses/$courseTitle'
    | '/_layout/(teacher)/courses/$courseTltle'
    | '/_layout/(student)/enrolledCoursses/'
    | '/_layout/(teacher)/courses/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/about",
        "/(auth)/login",
        "/(auth)/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/profile",
        "/_layout/",
        "/_layout/(admin)/addUser",
        "/_layout/(admin)/dashboard",
        "/_layout/(student)/enrolledCourses",
        "/_layout/(student)/joinLive",
        "/_layout/(student)/notes",
        "/_layout/(teacher)/courses",
        "/_layout/(teacher)/hostLive",
        "/_layout/(student)/enrolledCoursses/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx"
    },
    "/_layout/profile": {
      "filePath": "_layout/profile.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/(admin)/addUser": {
      "filePath": "_layout/(admin)/addUser.tsx",
      "parent": "/_layout"
    },
    "/_layout/(admin)/dashboard": {
      "filePath": "_layout/(admin)/dashboard.tsx",
      "parent": "/_layout"
    },
    "/_layout/(student)/enrolledCourses": {
      "filePath": "_layout/(student)/enrolledCourses.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/(student)/enrolledCourses/$courseTitle"
      ]
    },
    "/_layout/(student)/joinLive": {
      "filePath": "_layout/(student)/joinLive.tsx",
      "parent": "/_layout"
    },
    "/_layout/(student)/notes": {
      "filePath": "_layout/(student)/notes.tsx",
      "parent": "/_layout"
    },
    "/_layout/(teacher)/courses": {
      "filePath": "_layout/(teacher)/courses.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/(teacher)/courses/$courseTltle",
        "/_layout/(teacher)/courses/"
      ]
    },
    "/_layout/(teacher)/hostLive": {
      "filePath": "_layout/(teacher)/hostLive.tsx",
      "parent": "/_layout"
    },
    "/_layout/(student)/enrolledCourses/$courseTitle": {
      "filePath": "_layout/(student)/enrolledCourses.$courseTitle.tsx",
      "parent": "/_layout/(student)/enrolledCourses"
    },
    "/_layout/(teacher)/courses/$courseTltle": {
      "filePath": "_layout/(teacher)/courses.$courseTltle.tsx",
      "parent": "/_layout/(teacher)/courses"
    },
    "/_layout/(student)/enrolledCoursses/": {
      "filePath": "_layout/(student)/enrolledCoursses.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/(teacher)/courses/": {
      "filePath": "_layout/(teacher)/courses.index.tsx",
      "parent": "/_layout/(teacher)/courses"
    }
  }
}
ROUTE_MANIFEST_END */
